version: '3.8'

services:
  traumst-api:
    build:
      context: .
      dockerfile: Dockerfile
      target: api
    image: traumst-api:v1
    ports:
      - "7654:7654"
    environment:
      - LISTEN_PORT=${LISTEN_PORT}
      - SMTP_PASS=${SMTP_PASS}
      - SMTP_USER=${SMTP_USER}
      - EMAIL_RECEIVER=${EMAIL_RECEIVER}

  traumst-website:
    build:
      context: .
      dockerfile: Dockerfile
      target: website
    image: traumst-website:v1
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./.ssl:/etc/nginx/ssl