version: '3.8'

volumes:
  traumst-vol:
    driver: local

services:
  traumst-api:
    container_name: api
    build:
      context: .
      dockerfile: Dockerfile
      target: api
    image: traumst-api:v3
    ports:
      - "${LISTEN_PORT}:${LISTEN_PORT}"
    environment:
      - LISTEN_PORT=${LISTEN_PORT}
      - SMTP_PASS=${SMTP_PASS}
      - SMTP_USER=${SMTP_USER}
      - EMAIL_RECEIVER=${EMAIL_RECEIVER}
      - DB_CONN=${DB_CONN}
      - DB_CONN_POOL=${DB_CONN_POOL}
    volumes:
      - traumst-vol:/data

  traumst-web:
    container_name: web
    build:
      context: .
      dockerfile: Dockerfile
      target: web
    image: traumst-web:v3
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./.ssl:/etc/nginx/ssl