version: '3.8'

services:
  traumst-api:
    build:
      context: .
      dockerfile: Dockerfile
    image: traumst-api:v1
    ports:
      - "${LISTEN_PORT}:${LISTEN_PORT}"
    environment:
      - LISTEN_PORT=${LISTEN_PORT}
      - SMTP_PASS=${SMTP_PASS}
      - SMTP_USER=${SMTP_USER}
      - EMAIL_RECEIVER=${EMAIL_RECEIVER}

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./.ssl:/etc/nginx/ssl