name: Deploy

on:
  workflow_dispatch:

jobs:
  build_and_push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push traumst-api image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/traumst-api:v1 --target api .
          docker push ${{ secrets.DOCKER_USERNAME }}/traumst-api:v1

      - name: Build and push traumst-website image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/traumst-website:v1 --target website .
          docker push ${{ secrets.DOCKER_USERNAME }}/traumst-website:v1

  deploy:
    runs-on: [ self-hosted, linux ]
    needs: build_and_push
    env:
      LISTEN_PORT: ${{ secrets.LISTEN_PORT }}
      SMTP_PASS: ${{ secrets.SMTP_PASS }}
      SMTP_USER: ${{ secrets.SMTP_USER }}
      EMAIL_RECEIVER: ${{ secrets.EMAIL_RECEIVER }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Substitute environment variables in nginx configuration
        run: |
          envsubst '${LISTEN_PORT}' < nginx.conf.template > nginx.conf

      - name: Create SSL certificate and private key
        run: |
          rm -rf .ssl
          mkdir -p .ssl
          echo "${{ secrets.SSL_CERTIFICATE }}" > .ssl/alextech_pro.crt
          echo "${{ secrets.SSL_PRIVATE_KEY }}" > .ssl/alextech_pro.key

      - name: Deploy with docker-compose
        run: |
          docker-compose down
          export LISTEN_PORT=${{ secrets.LISTEN_PORT }}
          export SMTP_PASS=${{ secrets.SMTP_PASS }}
          export SMTP_USER=${{ secrets.SMTP_USER }}
          export EMAIL_RECEIVER=${{ secrets.EMAIL_RECEIVER }}
          docker-compose up --build -d traumst-api || exit 111
          docker-compose up --build -d traumst-website || exit 111
          docker system prune