name: Deploy

on:
  push:
    branches:
      - main

jobs:
  build_and_push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push traumst-api image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/traumst-api:v1 --target api .
          docker push ${{ secrets.DOCKER_USERNAME }}/traumst-api:v1

      - name: Build and push traumst-website image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/traumst-website:v1 --target website .
          docker push ${{ secrets.DOCKER_USERNAME }}/traumst-website:v1

  deploy:
    runs-on: [ self-hosted, linux ]
    needs: build_and_push
    env:
      LISTEN_PORT: ${{ secrets.LISTEN_PORT }}
      SMTP_PASS: ${{ secrets.SMTP_PASS }}
      SMTP_USER: ${{ secrets.SMTP_USER }}
      EMAIL_RECEIVER: ${{ secrets.EMAIL_RECEIVER }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Debug print environment variables
        run: |
          echo "LISTEN_PORT=$LISTEN_PORT"
          # Don't print SMTP_PASS for security reasons
          echo "SMTP_USER=$SMTP_USER"
          echo "EMAIL_RECEIVER=$EMAIL_RECEIVER"

      - name: Substitute environment variables in nginx configuration
        run: |
          envsubst '${LISTEN_PORT}' < nginx.conf.template > nginx.conf

      - name: Deploy with docker-compose
        run: |
          docker-compose up --build -d