name: Deploy to DigitalOcean

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/traumst-api:latest .
          docker push ${{ secrets.DOCKER_USERNAME }}/traumst-api:latest

  deploy-to-digitalocean:
    needs: build-and-push
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to DigitalOcean
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.DO_DROPLET_IP }}
          username: root
          key: ${{ secrets.DO_SSH_PRIVATE_KEY }}
          script: |
            echo "${{ secrets.ENV_FILE_CONTENT }}" > ~/.env
            docker pull ${{ secrets.DOCKER_USERNAME }}/traumst-api:latest
            docker stop traumst-api-container || true
            docker rm traumst-api-container || true
            set -a; source ~/.env; set +a
            docker run -d -p 7654:7654 \
            -e LISTEN_PORT \
            -e SMTP_PASS \
            -e SMTP_USER \
            -e EMAIL_RECEIVER \
            -v ~/.env:/app/.env \
            --name traumst-api-container \
            --restart always \
            ${{ secrets.DOCKER_USERNAME }}/traumst-api:latest