name: build and deploy

on:
  workflow_dispatch:

jobs:
  build_and_push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push traumst-api image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/traumst-api:v4 --target api .
          docker push ${{ secrets.DOCKER_USERNAME }}/traumst-api:v4

      - name: Build and push traumst-website image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/traumst-web:v4 --target web .
          docker push ${{ secrets.DOCKER_USERNAME }}/traumst-web:v4

  deploy:
    runs-on: [ self-hosted, linux ]
    needs: build_and_push
    env:
      LISTEN_PORT: ${{ secrets.LISTEN_PORT }}
      SMTP_PASS: ${{ secrets.SMTP_PASS }}
      SMTP_USER: ${{ secrets.SMTP_USER }}
      EMAIL_RECEIVER: ${{ secrets.EMAIL_RECEIVER }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Substitute environment variables in nginx configuration
        run: |
          envsubst '${LISTEN_PORT}' < nginx.conf.template > nginx.conf

      - name: Create SSL certificate and private key
        run: |
          rm -rf .ssl
          mkdir -p .ssl
          echo "${{ secrets.SSL_CRT }}" > .ssl/alextech_pro.crt
          echo "${{ secrets.SSL_KEY }}" > .ssl/alextech_pro.key

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # rollback here only rolls back 'api' container
      - name: Pull and Deploy traumst-api
        run: |
          docker-compose pull traumst-api
          if [ $(docker ps -q -f name=api) ]; then
            docker stop api
            docker rm api
          fi
          docker-compose up -d traumst-api || exit 111

      # rollback here only rolls back 'web' container
      - name: Pull and Deploy traumst-web
        run: |
          docker-compose pull traumst-web
          if [ $(docker ps -q -f name=web) ]; then
            docker stop web
            docker rm web
          fi
          docker-compose up -d traumst-web || exit 222

      - name: Cleanup
        run: docker system prune -a -f