name: Deploy to DigitalOcean

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push API Docker image
        run: |
          docker build --target api -t ${{ secrets.DOCKER_USERNAME }}/traumst-api:latest .
          docker push ${{ secrets.DOCKER_USERNAME }}/traumst-api:latest

      - name: Build and Push Website Docker image
        run: |
          docker build --target website -t ${{ secrets.DOCKER_USERNAME }}/traumst-website:latest .
          docker push ${{ secrets.DOCKER_USERNAME }}/traumst-website:latest

      - name: Template nginx.conf
        run: |
          envsubst '${LISTEN_PORT}' < nginx.conf.template > nginx.conf

  deploy-to-digitalocean:
    needs: build-and-push
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to DigitalOcean
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.DO_DROPLET_IP }}
          username: root
          key: ${{ secrets.DO_SSH_PRIVATE_KEY }}
          script: |
            echo "${{ secrets.ENV_FILE_CONTENT }}" > ~/.env
            
            # Copy SSL certificates and nginx.conf
            echo "${{ secrets.SSL_CRT }}" > ~/.ssl/alextech_pro.crt
            echo "${{ secrets.SSL_KEY }}" > ~/.ssl/alextech_pro.key
            scp nginx.conf root@${{ secrets.DO_DROPLET_IP }}:~/nginx.conf
            
            # Create the docker-compose.yml file on the remote server
            echo "
            version: '3.8'
            
            services:
              traumst-api:
                image: ${{ secrets.DOCKER_USERNAME }}/traumst-api:latest
                ports:
                  - '7654:7654'
                environment:
                  - LISTEN_PORT=${LISTEN_PORT}
                  - SMTP_PASS=${SMTP_PASS}
                  - SMTP_USER=${SMTP_USER}
                  - EMAIL_RECEIVER=${EMAIL_RECEIVER}

              traumst-website:
                image: ${{ secrets.DOCKER_USERNAME }}/traumst-website:latest
                ports:
                  - '80:80'
                  - '443:443'
                volumes:
                  - ~/nginx.conf:/etc/nginx/conf.d/default.conf
                  - ~/.ssl:/etc/nginx/ssl
            " > ~/docker-compose.yml

            # Starting the services using docker-compose
            docker-compose -f ~/docker-compose.yml up -d